// <auto-generated />
using System;
using GerenciaProjeto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GerenciaProjeto.Migrations
{
    [DbContext(typeof(GerenciaProjetoContext))]
    [Migration("20210604140601_Criada_EmpresaSistema")]
    partial class Criada_EmpresaSistema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleTarefas.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnName("telefone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("empresa","tarefas");
                });

            modelBuilder.Entity("ControleTarefas.Models.EmpresaSistema", b =>
                {
                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.HasKey("EmpresaId", "SistemaId");

                    b.HasIndex("SistemaId");

                    b.ToTable("EmpresaSistema");
                });

            modelBuilder.Entity("ControleTarefas.Models.HistoricoVersoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<int?>("VersaoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int?>("VersaoAtualizadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SistemaId");

                    b.HasIndex("VersaoAnteriorId");

                    b.HasIndex("VersaoAtualizadaId");

                    b.ToTable("HistoricoVersoes");
                });

            modelBuilder.Entity("ControleTarefas.Models.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sistema");
                });

            modelBuilder.Entity("ControleTarefas.Models.TarefaCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnName("dataFinal")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DataInicial")
                        .HasColumnName("dataInicial")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("EmpresaId")
                        .HasColumnName("empresaId")
                        .HasColumnType("int");

                    b.Property<string>("Erro")
                        .HasColumnName("erro")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Funcionario")
                        .HasColumnName("funcionario")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Motivo")
                        .HasColumnName("motivo")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Solucao")
                        .HasColumnName("solucao")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasName("tarefacliente_ibfk_1");

                    b.ToTable("tarefacliente","tarefas");
                });

            modelBuilder.Entity("ControleTarefas.Models.TarefaEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acao")
                        .HasColumnName("acao")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnName("dataFinal")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DataInicial")
                        .HasColumnName("dataInicial")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Observacao")
                        .HasColumnName("observacao")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasName("id_status");

                    b.ToTable("tarefaempresa","tarefas");
                });

            modelBuilder.Entity("ControleTarefas.Models.Versao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SistemaId");

                    b.ToTable("Versao");
                });

            modelBuilder.Entity("ControleTarefas.Models.EmpresaSistema", b =>
                {
                    b.HasOne("ControleTarefas.Models.Empresa", "Empresa")
                        .WithMany("Sistemas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTarefas.Models.Sistema", "Sistema")
                        .WithMany("Empresas")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleTarefas.Models.HistoricoVersoes", b =>
                {
                    b.HasOne("ControleTarefas.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTarefas.Models.Sistema", "Sistema")
                        .WithMany()
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleTarefas.Models.Versao", "VersaoAnterior")
                        .WithMany()
                        .HasForeignKey("VersaoAnteriorId");

                    b.HasOne("ControleTarefas.Models.Versao", "VersaoAtualizada")
                        .WithMany()
                        .HasForeignKey("VersaoAtualizadaId");
                });

            modelBuilder.Entity("ControleTarefas.Models.TarefaCliente", b =>
                {
                    b.HasOne("ControleTarefas.Models.Empresa", "Empresa")
                        .WithMany("TarefasCliente")
                        .HasForeignKey("EmpresaId")
                        .HasConstraintName("tarefacliente$tarefacliente_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleTarefas.Models.Versao", b =>
                {
                    b.HasOne("ControleTarefas.Models.Sistema", "Sistema")
                        .WithMany("Versoes")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
